
CREATE DATABASE IF NOT EXISTS orders;
USE orders;

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(500) DEFAULT '/assets/man.jpg',
    shipping_address VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add missing columns to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500) DEFAULT '/assets/man.jpg';
ALTER TABLE users ADD COLUMN IF NOT EXISTS shipping_address VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS balance DECIMAL(10,2) DEFAULT 0.00;

-- DISCOUNT_CODES TABLE
CREATE TABLE IF NOT EXISTS discount_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    discount_type ENUM('percent', 'fixed') NOT NULL DEFAULT 'percent',
    discount_value DECIMAL(10,2) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    expires_at DATETIME DEFAULT NULL,
    max_uses INT NOT NULL DEFAULT -1,
    uses INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add missing columns to discount_codes
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS discount_type ENUM('percent', 'fixed') NOT NULL DEFAULT 'percent';
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS discount_value DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS expires_at DATETIME DEFAULT NULL;
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS max_uses INT NOT NULL DEFAULT -1;
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS uses INT NOT NULL DEFAULT 0;
ALTER TABLE discount_codes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    plastic VARCHAR(50) NOT NULL,
    weight INT NOT NULL,
    delivery VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    fulfilled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('pending', 'confirmed', 'completed', 'cancelled') DEFAULT 'pending',
    description TEXT,
    amount DECIMAL(10,2),
    delivery_time VARCHAR(100),
    shipping_location VARCHAR(50) NOT NULL DEFAULT 'Barrow',
    discount_code_id INT DEFAULT NULL,
    discount_applied DECIMAL(10,2) DEFAULT 0.00,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (discount_code_id) REFERENCES discount_codes(id)
);

-- Add missing columns to orders
ALTER TABLE orders ADD COLUMN IF NOT EXISTS model_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS plastic VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS weight INT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fulfilled BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS status ENUM('pending', 'confirmed', 'completed', 'cancelled') DEFAULT 'pending';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS amount DECIMAL(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_time VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_location VARCHAR(50) NOT NULL DEFAULT 'Barrow';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_code_id INT DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_applied DECIMAL(10,2) DEFAULT 0.00;
